# Generated by Django 4.2.6 on 2023-10-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='update_date',
            new_name='updated_date',
        ),
    ]
