# Generated by Django 4.2.6 on 2023-10-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_countedviews_post_counted_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='createdDate',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publishedDate',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updatedDate',
            new_name='updated_date',
        ),
    ]
